[changelog]
body = """
{% if version %}\
{% else %}\
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](<REPO>/commit/{{ commit.id }}))\
    {% endfor %}
{% endfor %}
"""
trim = true
render_always = true
postprocessors = [
    { pattern = '<REPO>', replace = "https://github.com/bk-bf/Fantasia4x" },
]

[git]
conventional_commits = true
filter_unconventional = true
require_conventional = false
split_commits = false
commit_preprocessors = [
]
protect_breaking_commits = false
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->🚀 Features" },
    { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
    { message = "^perf", group = "<!-- 2 -->⚡ Performance" },
    { message = "^revert", group = "<!-- 3 -->◀️ Revert" },
    { body = ".*security", group = "<!-- 4 -->🛡️ Security" },
    { message = "^docs?", skip = true },
    { message = "^style", skip = true },
    { message = "^test", skip = true },
    { message = "^refactor", skip = true },
    { message = "^chore", skip = true },
    { message = "^ci", skip = true },
    { message = "^build", skip = true },
    { message = ".*", skip = true },
]
filter_commits = false
fail_on_unmatched_commit = false
link_parsers = []
use_branch_tags = false
topo_order = false
topo_order_commits = true
sort_commits = "oldest"
recurse_submodules = false
