name: tps

on:
  workflow_dispatch:

concurrency:
  group: tps-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tps:
    runs-on: codspeed-macro
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/prepare

      - name: Ticks per second, wall time
        uses: CodSpeedHQ/action@v5
        with:
          mode: walltime
          run: pnpm bench:tps
